path: /home/phillip/Desktop/todays_tutorial/38_yolov8_train_custom_model/code/data # dataset path,  use absolute path
train: images # training images
val: val_images # validation images

# Classes
names:
  0: license plate
