path: /home/train_yolov8/dataset/ # dataset path,  use absolute path
train: /home/train_yolov8/dataset/images # training images
val: /home/train_yolov8/val_images # validation images

# path: images_dataset
# train: images_dataset/images
# val: val_images

# Classes
names:
  0: license plate
